[package]
name = "aoc_{{YEAR}}_day_{{DAY}}"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true }
simplelog = { workspace = true }

[dev-dependencies]
claim = { workspace = true }

[lints]
workspace = true
