[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true }
simplelog = { workspace = true }

[dev-dependencies]
claim = { workspace = true }

[lints]
workspace = true

